### ISSUE TITLE
Bright screen

### ISSUE THREAD

**Issue by ArthurGS-tech** [ZalithLauncher/ZalithLauncher#346]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

When start the version and in the version it start to bright up i don't know what happen
![Screenshot_2024-12-29-10-20-24-93](https://github.com/user-attachments/assets/18e4bb42-7977-4c54-84c0-93445bfdf655)

### Log File / 日志文件

2024-12-29 10:23:31,302 main ERROR appender Console has no parameter that matches element Policies

Registered forkAndExec
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[10:23:34] [Client thread/INFO]: Setting user: Arthur Gabriel
[10:23:41] [Client thread/WARN]: Skipping bad option: lastServer:
[10:23:41] [Client thread/INFO]: LWJGL Version: 3.3.3-snapshot
[10:23:41] [Client thread/INFO]: [STDOUT]: LWJGLX: GL caps init
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
Extension GL_EXT_draw_buffers  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_multi_draw_arrays  detected
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_OES_fragment_precision_high  detected and used
Extension GL_EXT_shader_texture_lod detected and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 4096
Max Varying Vector: 15
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 2
Hardware vendor is Imagination Technologies
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/storage/emulated/0/games/ZalithLauncher/.minecraft
[10:23:42] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[10:23:42] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.Pointer$Default.<init>(Pointer.java:88)
[10:23:42] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.CustomBuffer.<init>(CustomBuffer.java:25)
[10:23:42] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.StructBuffer.<init>(StructBuffer.java:20)
[10:23:42] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWImage$Buffer.<init>(GLFWImage.java:303)
[10:23:42] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.Display.setIcon(Display.java:946)
[10:23:42] [Client thread/INFO]: [STDERR]: 	at bib.av(SourceFile:661)
[10:23:42] [Client thread/INFO]: [STDERR]: 	at bib.aq(SourceFile:456)
[10:23:42] [Client thread/INFO]: [STDERR]: 	at bib.a(SourceFile:404)
[10:23:42] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
EGLBridge: Binding to OpenGL ES
[10:23:42] [Client thread/INFO]: [STDOUT]: LWJGLX: ready-handle context created
[10:23:42] [Client thread/INFO]: [STDOUT]: Grab: false
[10:23:43] [Client thread/INFO]: Reloading ResourceManager: Default
[10:23:44] [Sound Library Loader/INFO]: Starting up SoundSystem...
[10:23:44] [Thread-2/INFO]: Initializing LWJGL OpenAL
[10:23:44] [Thread-2/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[10:23:45] [Thread-2/INFO]: OpenAL initialized.
[10:23:45] [Sound Library Loader/INFO]: Sound engine started
[10:23:58] [Client thread/INFO]: Created: 1024x512 textures-atlas
[10:24:05] [Client thread/WARN]: Failed to load shader: minecraft:shaders/post/entity_outline.json
nj: Invalid shaders/program/entity_sobel.fsh: Couldn't compile fragment program: Compile failed.
ERROR: 0:65: 'texture2D' : undeclared identifier
ERROR: 0:65: invalid function call
2 compilation errors. No code generated.
	at cda.a(SourceFile:70) ~[1.12.2.jar:?]
	at ccx.<init>(SourceFile:134) ~[1.12.2.jar:?]
	at ccz.<init>(SourceFile:28) ~[1.12.2.jar:?]
	at ccy.a(SourceFile:274) ~[1.12.2.jar:?]
	at ccy.a(SourceFile:141) ~[1.12.2.jar:?]
	at ccy.a(SourceFile:89) ~[1.12.2.jar:?]
	at ccy.<init>(SourceFile:56) ~[1.12.2.jar:?]
	at buy.b(SourceFile:246) [1.12.2.jar:?]
	at bib.aq(SourceFile:582) [1.12.2.jar:?]
	at bib.a(SourceFile:404) [1.12.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [1.12.2.jar:?]
[10:24:15] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id

### Screenshots or Videos / 截图或视频

![Screenshot_2024-12-29-10-20-24-93](https://github.com/user-attachments/assets/bbd48830-90dd-4700-a9b9-6141ca2e369f)

### Reproduction Steps / 复现步骤

```markdown
1. Start the version
2. Wait
```

### Android Version / Android 版本

9

### App Version / 应用版本

1.3.9.1

### Selected Renderer / 选择的渲染器

GL4ES

### Device Information / 设备信息

Oppo A12, Android 9, 

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
https://github.com/ZalithLauncher/ZalithLauncher/commit/bf968fb792101c3c97d29e17261c82633cdce89f

**Comment by ArthurGS-tech** [comment]
What should i do i didn't understand
